// <auto-generated />
using ApolloIntegration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApolloIntegration.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220613213218_AddKeywords")]
    partial class AddKeywords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ApolloIntegration.Domain.Entities.ApolloContact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ApolloId")
                        .HasColumnType("text");

                    b.Property<string>("JsonData")
                        .HasColumnType("jsonb");

                    b.HasKey("id");

                    b.ToTable("ApolloContact");
                });

            modelBuilder.Entity("ApolloIntegration.Domain.Entities.ApolloKeyword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Keyword")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ApolloKeyword");
                });
#pragma warning restore 612, 618
        }
    }
}
